---
title: Teken een driehoek
hero_image: images/banner.png
description: Teken een driehoek met Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - 
    title: Inleiding
