title: Draw a triangle
hero_image: images/banner.png
description: Draw a triangle in processing with Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - title: Introduction
