---
title: Dibuja un triángulo
hero_image: images/banner.png
description: Dibuja un triángulo usando funciones de Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - 
    title: Introducción
