---
title: Llunio triongl
hero_image: images/banner.png
description: Llunio triongl wrth brosesu gyda Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - 
    title: Cyflwyniad
