---
title: Zeichne ein Dreieck
hero_image: images/banner.png
description: Zeichne ein Dreieck in Processing mit Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - 
    title: Einleitung
