---
title: Desenhe um triângulo
hero_image: images/banner.png
description: Desenhe um triângulo em Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - title: Introdução
