---
title: Narysuj trójkąt
hero_image: images/banner.png
description: Narysuj trójkąt za pomocą przetwarzania w Pythonie
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - title: Wprowadzenie
