---
title: Σχεδίασε ένα τρίγωνο
hero_image: images/banner.png
description: Σχεδίασε ένα τρίγωνο με Python
version: 4
listed: false
copyedit: false
last_tested: "2021-07-22"
steps:
  - title: Εισαγωγή
